name: Action

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule: [cron: "30 4 * * *"]

jobs:
  Main:
    runs-on: ubuntu/latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with: { go-version-file: go.mod, cache: true }
      - uses: ufukty/golistics@v0.2.2
